### PR TITLE
Show VPN links on map

### LINKED ISSUE #42: VPN Links?
Hello,
I was just wondering what you guys would think of showing our VPN links to our remote PittMesh locations on the map? Perhaps instead of a red line they could be a blue line or something of the like. Just to show that those portions are still connected to the larger network. 

Let me know what you guys think.

### PR DESCRIPTION
**Pull request by colindean**
Closes #42 

screen shot 2016-07-18 at 18 40 54

### CODE REVIEW

**Comment by colindean** [comment]
@Protagonistics could look at this or just be surprised when @Justin417 merges it ;-)

**Comment by Protagonistics** [comment]
I don't see the lines.

**Comment by colindean** [comment]
It's working on prod for me.

**Comment by Justin417** [comment]
Looks great!

**Pull request merged**
